name = "Kyles Pokepack"
author = "Kylego"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bd53855a2e1ce58a2768d6d823622962e5514d5e2dc02ef08d3ee9fb1438328"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.210"
